ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend-service
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: backend-service
            port: 3001
          secret:
            ATLAS_URI: "mongodb+srv://kushalrao103:eZgLARR1p2xSGfGU@cluster0.1a3iq.mongodb.net/Learner_Report?retryWrites=true&w=majority"
            HASH_KEY: "thisIsMyHashKey"
            JWT_SECRET_KEY: "thisIsMyJwtSecretKey"

