apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  ATLAS_URI: {{ .Values.backend.secret.ATLAS_URI | quote }}
  HASH_KEY: {{ .Values.backend.secret.HASH_KEY | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.secret.JWT_SECRET_KEY | quote }}
